### PR TITLE
Remove dependencies for downloading / unzipping

### PR DESCRIPTION
**Pull request by octref**
WIP. I plan to allow `downloadAndUnzipVSCode` to take a version too.

```ts
type Version = 'Insiders' | '1.32.0' | '1.31.1' | '1.31.0' ...
```

The script would download them to:

```
.vscode-test/
  /insiders
  /stable-1.32.0
  /stable-1.31.1
  /stable-1.31.0
  ...
```

@bpasero I'm wondering if we can also change the way we run test. Instead of saying users should run `node ./node_modules/bin/test`, maybe export a `runTest` function so it's easier to configure?

User's code could look like this:

```ts
import { runTests } from 'vscode-test';

async function go() {
  const vscodeExecutablePath = await downloadAndUnzipVSCode()

  const extPath = path.resolve(__dirname, '../../')
  const testPath = path.resolve(__dirname, '../test')
  const testWorkspace = path.resolve(__dirname, '../fixture')

  runTests(vscodeExecutablePath, extPath, testPath, testWorkspace)
}
```

### CODE REVIEW

**Comment by bpasero** [comment]
@octref 

> @bpasero I'm wondering if we can also change the way we run test. Instead of saying users should run node ./node_modules/bin/test, maybe export a runTest function so it's easier to configure?

How would that work for extensions? Today we have the following command configuration in `package.json`:

```json
"scripts": {
	"vscode:prepublish": "npm run compile",
	"compile": "tsc -p ./",
	"watch": "tsc -watch -p ./",
	"postinstall": "node ./node_modules/vscode/bin/install",
	"test": "npm run compile && node ./node_modules/vscode/bin/test"
}
```

How would the `test` command look like?

**Comment by bpasero** [comment]
@octref btw I am not 100% sure removing the `request` library is wise. Are we certain we can handle things like proxy support properly without it?

**Comment by octref** [comment]
@bpasero 

Something like this: https://github.com/octref/vscode-test-ext/blob/master/package.json#L27

Also would make #111 and #124 possible, you can just install dependencies for fixture projects or 3rd party extensions yourself before running the tests.

Instead of implicit flags on CLI, we can now properly document and IntelliSense the options.

**Comment by octref** [comment]
> Are we certain we can handle things like proxy support properly without it?

I'll bring it back with https://github.com/TooTallNate/node-https-proxy-agent. `request` has many features we never use.

**Comment by bpasero** [comment]
@octref we cannot really remove that test script though right? Because by now every extension has it in its `package.json` and we cannot update extensions to the newer solution?

**Comment by octref** [comment]
@bpasero We could include the test script and still export the `runTest` function to users, so they can opt-in. But I think we should really move that to a dedicated module such as `vscode-test`.

If we do have https://github.com/Microsoft/vscode-extension-vscode/issues/147 then we can start deprecating `vscode` module and add a warning to the test script, and maybe remove it sometime in the future.

**Comment by bpasero** [comment]
@octref I think we can keep the test script in `package.json` but point into a script exposed from `vscode-test` NPM module without issues. That way we are not breaking or need any deprecation.

**Comment by octref** [comment]
> I think we can keep the test script in package.json but point into a script exposed from vscode-test NPM module without issues. That way we are not breaking or need any deprecation.

Sounds great. I can do that.

**Comment by octref** [comment]
I think this is ready to review. I published https://github.com/microsoft/vscode-test and https://www.npmjs.com/package/vscode-test. You can see https://github.com/octref/vscode-test-sample for sample usage.

Things I added:

- Simpler API. Now you can `runTest` without worrying about downloading & unzipping VS Code, but you do have the options to manually do that.
- Proxy support.
- Insider download support.

I didn't move the test runner yet. I can do that after this gets merged.

**Comment by bpasero** [comment]
@octref great work, this makes the module much smaller. A few comments:
* since you already started with converting test to use more modern ES6 features I suggest we do the same for `install` too
* I am a little bit confused about the explicit listing of all versions of VSCode in `lib/download.ts`. We should not have a system where we need to update either `vscode-test` nor `vscode` module when doing a release
* you seem to be shipping the *.ts files with the module:

image

PS: should we switch to be using `yarn` for this module?

**Comment by octref** [comment]
> we do the same for install too

I can do that through another PR, but I thought we are moving away from postinstall scripts to directing people to install through `@type/vscode`: https://github.com/Microsoft/vscode/issues/70175.

> listing of all versions of VSCode in lib/download.ts

Agreed. Removed it and is using https://update.code.visualstudio.com/api/releases/stable for validating version. https://github.com/Microsoft/vscode-test/commit/646c00533821d9a57344a078defb73d2db8fa325

> you seem to be shipping the *.ts files with the module:

Fixed.

> should we switch to be using yarn for this module?

I think so. Me and Martin switched all satellite repos to using yarn.

**Comment by bpasero** [comment]
> I can do that through another PR, but I thought we are moving away from postinstall scripts to directing people to install through @type/vscode: Microsoft/vscode#70175.

Right. The challenge I see here is that we will always need a way to point to the latest `vscode.d.ts` on master. So we would need to publish to `@types/vscode` almost as part of our nightly build or have a workaround for this so that we can still point to new API that is not released yet.

> I think so. Me and Martin switched all satellite repos to using yarn.

Maybe that can be done as a separate PR.

Feel free to merge and publish under a new version 👍

**Comment by octref** [comment]
> the latest vscode.d.ts on master

I'll setup an Azure function that publishes our master/proposed API under NPM tag `nightly` and `proposed`.

Thanks for reviewing!

**Pull request merged**
