### PR TITLE
install dependencies before running tests

### PR DESCRIPTION
**Pull request by Sneezry**
If `CODE_INSTALL_DEPENDENCY` is set in environment variables, extension dependencies will be installed before running test

### CODE REVIEW

**Comment by lcampos** [comment]
Any chance this is still being considered for getting merged ? I'm currently running into an issue in which I could leverage this functionality. I'd be able to help out with testing/documenting it if that helps.

**Comment by octref** [comment]
Can you try using `vscode-test` directly and bring your own code for downloading dependencies? See https://github.com/octref/vscode-test-sample and https://github.com/microsoft/vscode-test.

For example:

```ts
import * as path from 'path'

import { runTests, downloadAndUnzipVSCode } from 'vscode-test'

async function go() {
  const vscodeExecutablePath = await downloadAndUnzipVSCode('1.30.0')

  // do your dependency installation by spawning `vscodeExecutablePath` with `--install-extensions`

  await runTests({
    vscodeExecutablePath,
    extensionPath,
    testRunnerPath,
    testWorkspace
  })
}
```

**Comment by octref** [comment]
We no longer use magical environment variables. Now you can use `vscode-test` API to do this easily:

```ts
out/test/**	const vscodeExecutablePath = await downloadAndUnzipVSCode('1.34.0');
child_process.spawnSync(vscodeExecutablePath, ['--install-extension', '<PATH-TO-VSIX>']);
```

Docs in https://github.com/microsoft/vscode-docs/pull/2695/files will be published next month.

**Comment by Eskibear** [comment]
@octref I'm not able to install extensions by `vscode-test`. 

In MacOSX, following https://github.com/microsoft/vscode-extension-vscode/pull/111#issuecomment-495428390 , the value of `vscodeExecutablePath ` is "/Users/travis/build/microsoft/vscode-java-debug/.vscode-test/vscode-1.36.1/Visual Studio Code.app/Contents/**MacOS/Electron**" , instead of real path of the code CLI. Thus `vscodeExecutablePath --install-extension path-to-vsix` simply opens a new instance of vscode and hangs there forever.

**Comment by octref** [comment]
@Eskibear You are right. It should have been `Contents/Resources/app/bin/code`. I'll fix it.

**Pull request closed without merging**
